# Generated by Django 5.0.3 on 2024-04-05 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_account_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='subscribed',
        ),
        migrations.AddField(
            model_name='account',
            name='last_paid',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
