# Generated by Django 5.0.3 on 2024-04-03 17:48

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_topic_slug_alter_topic_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer_text',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
