# Generated by Django 5.0.3 on 2024-04-03 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_addon'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addon',
            options={'ordering': ['-pub_date']},
        ),
    ]
