# Generated by Django 5.0.3 on 2024-04-04 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_addon_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
