# Generated by Django 5.0.3 on 2024-04-04 06:45

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_question_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text'),
        ),
    ]
