# Generated by Django 5.0.3 on 2024-04-07 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_transaction_use_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-date']},
        ),
    ]
